### ISSUE TITLE
Compiling on Mac OS X Yosemite fails

### ISSUE THREAD

**Issue by patcoll** [USU-Security/oip#1]
Almost got it to work. Steps I took:

    brew install libcryptopp sdl sdl_image libpcap freetype
    automake --add-missing
    autoconf
    ./configure
    make

Getting this error:

    /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
    g++  -g -O2   -o oipd config.o packetmanager.o clientpm.o clientmanager.o messages.o namecache.o encrypt.o hexprint.o oipd.o  -lfontconfig -lpcap -lcryptopp -lSDL_image -lSDL
    Undefined symbols for architecture x86_64:
      "_main", referenced from:
         implicit entry/start for main executable
         (maybe you meant: _SDL_main)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [oipd] Error 1
    make: *** [all] Error 2

g++:

    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
    Target: x86_64-apple-darwin14.0.0
    Thread model: posix

Homebrew deps:

    cryptopp: stable 5.6.2
    http://www.cryptopp.com/
    /usr/local/Cellar/cryptopp/5.6.2 (139 files,  11M) *
      Built from source
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/cryptopp.rb
    
    sdl: stable 1.2.15 (bottled), HEAD
    http://www.libsdl.org/
    /usr/local/Cellar/sdl/1.2.15 (223 files, 2.1M) *
      Poured from bottle
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sdl.rb
    ==> Options
    --universal
    	Build a universal binary
    --with-tests
    	Compile and install the tests
    --with-x11
    	Compile with support for X11 video driver
    --HEAD
    	Install HEAD version
    
    sdl_image: stable 1.2.12 (bottled)
    http://www.libsdl.org/projects/SDL_image
    /usr/local/Cellar/sdl_image/1.2.12_1 (8 files, 140K) *
      Poured from bottle
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/sdl_image.rb
    ==> Dependencies
    Build: pkg-config ✔
    Required: sdl ✔
    Recommended: jpeg ✔, libpng ✔, libtiff ✔, webp ✔
    ==> Options
    --universal
    	Build a universal binary
    --without-jpeg
    	Build without jpeg support
    --without-libpng
    	Build without libpng support
    --without-libtiff
    	Build without libtiff support
    --without-webp
    	Build without webp support
    
    libpcap: stable 1.6.2, HEAD
    http://www.tcpdump.org/
    
    This formula is keg-only.
    Mac OS X already provides this software and installing another version in
    parallel can cause all kinds of trouble.
    
    /usr/local/Cellar/libpcap/1.6.2_1 (80 files, 1.0M)
      Built from source
    From: https://github.com/homebrew/homebrew-dupes/blob/master/libpcap.rb
    
    freetype: stable 2.5.5 (bottled)
    http://www.freetype.org
    /usr/local/Cellar/freetype/2.5.3_1 (60 files, 2.5M) *
      Poured from bottle
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/freetype.rb
    ==> Dependencies
    Required: libpng ✔
    ==> Options
    --universal
    	Build a universal binary
    --without-subpixel
    	Disable sub-pixel rendering (a.k.a. LCD rendering, or ClearType)

**Comment by ekoyle** [comment]
Should be fixed now, although it appears that hardware acceleration is not working on OS X.
